import mongoose, { Document, Schema, Types } from 'mongoose';

export interface IUser extends Document {
  username: string;
  passwordHash: string;
  token: string;         // UUID auto-generated by plugin per RS account
  isAdmin: boolean;
  setupLinkUsed: boolean;
  communityEligible: boolean; // admin-granted: allowed to set up a community
  /** Personal Discord webhooks, set by the splasher themselves or by a community owner
   *  on their behalf. Additive with any community webhook(s) the splasher belongs to. */
  discordActiveWebhookUrl?: string;
  discordHistoryWebhookUrl?: string;
  /** This splasher's rank (and therefore hourly rate) in each community they belong to,
   *  keyed by Community _id. Decoupled from `Community.memberUserIds` on purpose — a rank
   *  assignment only matters once someone is a member, but membership itself is tracked there. */
  rankAssignments?: Map<string, Types.ObjectId>;
  createdAt: Date;
}

const UserSchema = new Schema<IUser>(
  {
    username: { type: String, required: true, unique: true, trim: true },
    passwordHash: { type: String, required: true },
    token: { type: String, required: true, unique: true },
    isAdmin: { type: Boolean, default: false },
    setupLinkUsed: { type: Boolean, default: false },
    communityEligible: { type: Boolean, default: false },
    discordActiveWebhookUrl: { type: String },
    discordHistoryWebhookUrl: { type: String },
    rankAssignments: { type: Map, of: Schema.Types.ObjectId },
  },
  { timestamps: { createdAt: 'createdAt', updatedAt: false } },
);

export const User = mongoose.model<IUser>('User', UserSchema);
