import mongoose, { Document, Schema } from 'mongoose';

export interface IUser extends Document {
  username: string;
  passwordHash: string;
  token: string;         // UUID auto-generated by plugin per RS account
  isAdmin: boolean;
  setupLinkUsed: boolean;
  createdAt: Date;
}

const UserSchema = new Schema<IUser>(
  {
    username: { type: String, required: true, unique: true, trim: true },
    passwordHash: { type: String, required: true },
    token: { type: String, required: true, unique: true },
    isAdmin: { type: Boolean, default: false },
    setupLinkUsed: { type: Boolean, default: false },
  },
  { timestamps: { createdAt: 'createdAt', updatedAt: false } },
);

export const User = mongoose.model<IUser>('User', UserSchema);
